games/urls.py
from django.urls import path

from games.views import MathFactsView, AnagramHuntView

app_name = 'games'
urlpatterns = [
    path('math-facts/', MathFactsView.as_view(), name='math-facts'),
    path('anagram-hunt/', AnagramHuntView.as_view(), name='anagram-hunt'),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView, GamesView, LoginView, ContactView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us', AboutUsView.as_view(), name='about-us'),
    path('games', GamesView.as_view(), name='games'),
    path('login', LoginView.as_view(), name='login'),
    path('contact', ContactView.as_view(), name='contact'),
]

play2learn/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from pages.views import HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("pages.urls")),
    path('games/', include("games.urls"))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pages/models.py
from django.db import models

# Create your models here.

games/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

class MathFactsView(TemplateView):
    template_name = "math-facts.html"

class AnagramHuntView(TemplateView):
    template_name = "anagram-hunt.html"

pages/views.py
from django.views.generic import TemplateView

# Create your views here.
# Home Page
class HomePageView(TemplateView):
    template_name = 'pages/home.html'

# About Us
class AboutUsView(TemplateView):
    template_name = 'pages/about_us.html'

# Games
class GamesView(TemplateView):
    template_name = 'pages/games.html'

# Login
class LoginView(TemplateView):
    template_name = 'pages/login.html'

# Contact Us
class ContactView(TemplateView):
    template_name = 'pages/contact.html'

templates/_base_vue - Copy.html
<!-- Play2Learn
  modified by: Karen DiCampo 
  8/23/2024
-->

<!-- https://html.spec.whatwg.org/multipage/syntax.html#the-doctype  
  and https://www.w3schools.com/tags/tag_doctype.asp
  show the keyword DOCTYPE in uppercase -->
<!DOCTYPE html>
{% load static %}
<!--  specify the language this file is written in and text flow-->
<html lang="en-us" dir="ltr">
<head>
  <meta charset="UTF-8">
  <!-- Wraps lines to the width of the device-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--This is the title that shows on  the browser tab -->
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap CSS CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <!--Add in the sitewide stylesheets-->
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/play2learn1.css' %}">
  <!--Fontawesome for envelope and social media icons-->
  <script src="https://kit.fontawesome.com/f804978a2a.js" crossorigin="anonymous"></script>
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg">
      <!--This inserts the logo-->
      <a class="navbar-brand" href="{% url 'pages:homepage' %}">
        <img src="{% static 'images/p2l1-237x100.png' %}" alt="Logo" class="img-fluid"/>
      </a>
      <!--This makes the company name a clickable link to home page-->
      <a class="navbar-brand" href="{% url 'pages:homepage' %}">Play2Learn</a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'pages:games' %}">Games</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'pages:about-us' %}">About</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'pages:login' %}">Login</a>
        </li>
      </ul>
    </nav>
  </header>

  {% block main %}{% endblock %}

  <footer class="fixed-bottom row">
    <div class="col">
      <div class="float-left">Copyright &copy; 2024 Play2Learn</div>
    </div>
    <div class="col">
      <div class="float-end">
        <section id="social">
          <ul>
            <li>
              <a href="{% url 'pages:contact' %}">Contact Us</a>
            </li>
            <l1>
              <a href = "https://instagram.com">Instagram</a>
            </l1>
            <li>
              <a href = "https://twitter.com">Twitter</a>
            </li>
            <li>
              <a href = "https://facebook.com">Facebook</a>
            </li>
          </ul>
        </section>
      </div>
    </div>

  </footer>
  <!--
    <div id="app"></div>
  -->

  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/_base_vue.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<!-- Bootstrap CSS CDN-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
<body>
  <header>
    <a href="{% url 'pages:homepage' %}">Home</a> | 
    <a href="{% url 'pages:about-us' %}">About</a> |
  </header>
  {% block main %}{% endblock %}
  <div id="app"></div>
  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/anagram-hunt.html
{% extends "_base_vue.html" %}

{% block title %}Anagram Hunt{% endblock %}
{% block main %}
  <h1>Anagram Hunt</h1>
  {{ block.super }}
{% endblock %} 

templates/math-facts.html
{% extends "_base_vue.html" %}

{% block title %}Math Facts{% endblock %}
{% block main %}
  <h1>Math Facts</h1>
  {{ block.super }}
{% endblock %}

templates/pages/about_us.html
{% extends "_base_vue.html" %}

{% block title %}About Us{% endblock %}
{% block header %}About Us{% endblock %}
<!-- Link to Style Sheets-->
<link rel="stylesheet" href="static/css/about.css">
{% block main %}
  <section id="page-info">
    <header id="page-header" class="text-center">
      <h2>About Us</h2>
      <img src="./static/images/LoveLearning1.jpeg" alt="book with heart and love to learn">
      <p>Play2Learn is a company of philomaths, which means lovers of learning.  
          At Play2Learn we love learning and creating games that make it enjoyable for others to learn.</p>
    </header>
  <section id="employees">

    <div class="card mb-3 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img 
                src="./static/images/Saraswati.jpeg"
                alt="image of Saraswati"
                class="img-fluid float-start" 
            />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Saraswati - President</h5>
              <p class="card-text">
                Saraswati is the goddess of intellect, wisdom and learning.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-3 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img 
                src="./static/images/Hephaestus.jpeg"
                alt="image of Hephaestus"
                class="img-fluid float-start" 
            />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Hephaestus - Game Designer</h5>
              <p class="card-text">
                Hephaestus is the God of Design & Creativity.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-3 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img 
                src="./static/images/Athena1.jpg"
                alt="image of Athena"
                class="img-fluid float-start" 
            />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Athena - Graphic Artist</h5>
              <p class="card-text">
                Athena is goddess of arts and crafts in greek methodology, She is the patronesses of all art forms.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-3 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img 
                src="./static/images/Seshat.jpeg"
                alt="image of Seshat"
                class="img-fluid float-start" 
            />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Seshat - Writer</h5>
              <p class="card-text">
                Seshat, whose name means “female scribe,” is the goddess of writing and record keeping.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-3 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img 
                src="./static/images/Pistis.jpeg"
                alt="image of Pistis"
                class="img-fluid float-start" 
            />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Pistis - Quality Assurance Specialist</h5>
              <p class="card-text">
                Pistis is the god of faith, trust and reliability.
              </p>
            </div>
          </div>
        </div>
      </div>

      <!-- The br creates a little space after the last div that is the same color as the body-->
      <br>
  </section> <!-- End Page-->
{% endblock %}

templates/pages/contact.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->
<!--This starts with the base html-->
{% extends "_base_vue.html" %}

<!--This is the title that shows on  the browser tab -->
{% block title %}P2L Home{% endblock %}
{% block header %}Play2Learn Contact{% endblock %}
{% block main %}
  <p>Welcome to Play2Learn Contact us</p>
{% endblock %}

templates/pages/games.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->
<!--This starts with the base html-->
{% extends "_base_vue.html" %}

<!--This is the title that shows on  the browser tab -->
{% block title %}P2L Home{% endblock %}
{% block header %}Play2Learn Home{% endblock %}
{% block main %}
  <p>Welcome to Play2Learn Games</p>
{% endblock %}

templates/pages/home - Copy.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->
<!--This starts with the base html-->
{% extends "_base_vue.html" %}

<!--This is the title that shows on  the browser tab -->
{% block title %}P2L Home{% endblock %}
{% block header %}Play2Learn Home{% endblock %}
{% block main %}
  <p>Welcome to Play2Learn Home</p>
{% endblock %}
{% block footer %}Play2Learn Home{% endblock %}

templates/pages/home copy.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->

<!-- https://html.spec.whatwg.org/multipage/syntax.html#the-doctype  
  and https://www.w3schools.com/tags/tag_doctype.asp
  show the keyword DOCTYPE in uppercase -->
<!DOCTYPE html>
<!--  specify the language this file is written in and text flow-->
<html lang="en-us" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <!-- Wraps lines to the width of the device-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--This is the title that shows on  the browser tab -->
    <link rel="icon" href="<%= BASE_URL %>/static/dist/js/favicon.ico">
    <title>P2L Home</title>
</head>
<body>
<p>Hello, Django!</p>
</body>
</html>

templates/pages/home.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->

{% extends "_base_vue.html" %}

{% block title %}P2L Home{% endblock %}
{% block header %}Play2Learn Home{% endblock %}
{% block main %}
  <p>Play2Learn Home</p>
{% endblock %}

templates/pages/login.html
<!-- Play2Learn
  by: Karen DiCampo 
  8/21/2024
-->
<!--This starts with the base html-->
{% extends "_base_vue.html" %}

<!--This is the title that shows on  the browser tab -->
{% block title %}P2L Home{% endblock %}
{% block header %}Play2Learn Home{% endblock %}
{% block main %}
  <p>Welcome to Play2Learn Login</p>
{% endblock %}